// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQys2xK7kmCnMWBASARl-ubLGffJCplc',
    appId: '1:738789205434:web:d5a3af551403ce48d52983',
    messagingSenderId: '738789205434',
    projectId: 'pathfinder-project-b212c',
    authDomain: 'pathfinder-project-b212c.firebaseapp.com',
    storageBucket: 'pathfinder-project-b212c.firebasestorage.app',
    measurementId: 'G-HZHYPRSNN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDum6d94l6wEeJf0UcVQwwX3bmZJwFtSSw',
    appId: '1:738789205434:android:080b96b73ecd6819d52983',
    messagingSenderId: '738789205434',
    projectId: 'pathfinder-project-b212c',
    storageBucket: 'pathfinder-project-b212c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMUkWwfuLLdp2a_4QeasbaGxuYkCvmoQ',
    appId: '1:738789205434:ios:1ea773cee3977a39d52983',
    messagingSenderId: '738789205434',
    projectId: 'pathfinder-project-b212c',
    storageBucket: 'pathfinder-project-b212c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMUkWwfuLLdp2a_4QeasbaGxuYkCvmoQ',
    appId: '1:738789205434:ios:1ea773cee3977a39d52983',
    messagingSenderId: '738789205434',
    projectId: 'pathfinder-project-b212c',
    storageBucket: 'pathfinder-project-b212c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASQys2xK7kmCnMWBASARl-ubLGffJCplc',
    appId: '1:738789205434:web:3e49593321f8803bd52983',
    messagingSenderId: '738789205434',
    projectId: 'pathfinder-project-b212c',
    authDomain: 'pathfinder-project-b212c.firebaseapp.com',
    storageBucket: 'pathfinder-project-b212c.firebasestorage.app',
    measurementId: 'G-SFPV06ZKXN',
  );
}
